"""Configuration & shared constants."""

from __future__ import annotations

import os

from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# Locations: normalized alias -> per-source codes
# ---------------------------------------------------------------------------

CITY_ALIASES: dict[str, list[str]] = {
    'an giang': ['an giang'],
    'ba ria vung tau': ['ba ria vung tau', 'vung tau', 'bà rịa vũng tàu', 'vũng tàu', 'bà rịa - vũng tàu', 'ba ria - vung tau'],
    'bac giang': ['bac giang', 'bắc giang'],
    'bac kan': ['bac kan', 'bắc kạn'],
    'bac lieu': ['bac lieu', 'bạc liêu'],
    'bac ninh': ['bac ninh', 'bắc ninh'],
    'ben tre': ['ben tre', 'bến tre'],
    'binh dinh': ['binh dinh', 'bình định'],
    'binh duong': ['binh duong', 'bình dương'],
    'binh phuoc': ['binh phuoc', 'bình phước'],
    'binh thuan': ['binh thuan', 'bình thuận'],
    'ca mau': ['ca mau', 'cà mau'],
    'cao bang': ['cao bang', 'cao bằng'],
    'can tho': ['can tho', 'cần thơ'],
    'da nang': ['da nang', 'dn', 'đà nẵng'],
    'dak lak': ['dak lak', 'đắk lắk'],
    'dak nong': ['dak nong', 'đắk nông'],
    'dien bien': ['dien bien', 'điện biên'],
    'dong nai': ['dong nai', 'đồng nai'],
    'dong thap': ['dong thap', 'đồng tháp'],
    'gia lai': ['gia lai'],
    'ha giang': ['ha giang', 'hà giang'],
    'ha nam': ['ha nam', 'hà nam'],
    'hanoi': ['ha noi', 'hn', 'hà nội'],
    'ha tinh': ['ha tinh', 'hà tĩnh'],
    'hai duong': ['hai duong', 'hải dương'],
    'hai phong': ['hai phong', 'hải phòng'],
    'hau giang': ['hau giang', 'hậu giang'],
    'hoa binh': ['hoa binh', 'hòa bình'],
    'ho chi minh': ['ho chi minh', 'hcm', 'hcmc', 'tphcm', 'tp.hcm', 'sai gon', 'saigon', 'hồ chí minh'],
    'hung yen': ['hung yen', 'hưng yên'],
    'khanh hoa': ['khanh hoa', 'nha trang', 'khánh hòa'],
    'kien giang': ['kien giang', 'phu quoc', 'kiên giang'],
    'kon tum': ['kon tum'],
    'lai chau': ['lai chau', 'lai châu'],
    'lam dong': ['lam dong', 'da lat', 'dalat', 'lâm đồng'],
    'lang son': ['lang son', 'lạng sơn'],
    'lao cai': ['lao cai', 'lào cai'],
    'long an': ['long an'],
    'nam dinh': ['nam dinh', 'nam định'],
    'nghe an': ['nghe an', 'vinh', 'nghệ an'],
    'ninh binh': ['ninh binh', 'ninh bình'],
    'ninh thuan': ['ninh thuan', 'ninh thuận'],
    'phu tho': ['phu tho', 'phú thọ'],
    'phu yen': ['phu yen', 'phú yên'],
    'quang binh': ['quang binh', 'quảng bình'],
    'quang nam': ['quang nam', 'quảng nam'],
    'quang ngai': ['quang ngai', 'quảng ngãi'],
    'quang ninh': ['quang ninh', 'ha long', 'quảng ninh'],
    'quang tri': ['quang tri', 'quảng trị'],
    'soc trang': ['soc trang', 'sóc trăng'],
    'son la': ['son la', 'sơn la'],
    'tay ninh': ['tay ninh', 'tây ninh'],
    'thai binh': ['thai binh', 'thái bình'],
    'thai nguyen': ['thai nguyen', 'thái nguyên'],
    'thanh hoa': ['thanh hoa', 'thanh hóa'],
    'thua thien hue': ['thua thien hue', 'hue', 'huế', 'thừa thiên huế'],
    'tien giang': ['tien giang', 'tiền giang'],
    'tra vinh': ['tra vinh', 'trà vinh'],
    'tuyen quang': ['tuyen quang', 'tuyên quang'],
    'vinh long': ['vinh long', 'vĩnh long'],
    'vinh phuc': ['vinh phuc', 'vĩnh phúc'],
    'yen bai': ['yen bai', 'yên bái'],
    'remote': ['remote', 'from anywhere', 'làm việc từ xa', '100% remote'],
    'international': ['international', 'quốc tế', 'nước ngoài', 'oversea', 'abroad'],
    'others': ['others', 'khác', 'other'],
}

VIETNAMWORKS_CITY_IDS: dict[str, int] = {
    'hanoi': 24,
    'ho chi minh': 29,
    'hai phong': 28,
    'da nang': 17,
    'can tho': 15,
    'ba ria vung tau': 3,
    'an giang': 2,
    'bac giang': 5,
    'bac kan': 4,
    'bac lieu': 6,
    'bac ninh': 7,
    'ben tre': 8,
    'binh dinh': 10,
    'binh duong': 11,
    'binh phuoc': 12,
    'binh thuan': 13,
    'ca mau': 14,
    'cao bang': 16,
    'dak lak': 18,
    'dak nong': 73,
    'dien bien': 69,
    'dong nai': 19,
    'dong thap': 20,
    'gia lai': 21,
    'ha giang': 22,
    'ha nam': 23,
    'ha tinh': 26,
    'hai duong': 27,
    'hau giang': 72,
    'hoa binh': 30,
    'hung yen': 32,
    'khanh hoa': 33,
    'kien giang': 61,
    'kon tum': 34,
    'lai chau': 35,
    'lam dong': 36,
    'lang son': 37,
    'lao cai': 38,
    'long an': 39,
    'nam dinh': 40,
    'nghe an': 41,
    'ninh binh': 42,
    'ninh thuan': 43,
    'phu tho': 44,
    'phu yen': 45,
    'quang binh': 46,
    'quang nam': 47,
    'quang ngai': 48,
    'quang ninh': 49,
    'quang tri': 50,
    'soc trang': 51,
    'son la': 52,
    'tay ninh': 53,
    'thai binh': 54,
    'thai nguyen': 55,
    'thanh hoa': 56,
    'thua thien hue': 57,
    'tien giang': 58,
    'tra vinh': 59,
    'tuyen quang': 60,
    'vinh long': 62,
    'vinh phuc': 63,
    'yen bai': 65,
    'international': 70,
}

TOPDEV_REGION_IDS: dict[str, str] = {
    'ho chi minh': '79',
    'hanoi': '01',
    'da nang': '48',
    'can tho': '92',
    'an giang': '89',
    'ba ria vung tau': '77',
    'binh duong': '74',
    'binh phuoc': '70',
    'binh thuan': '60',
    'binh dinh': '52',
    'bac lieu': '95',
    'bac giang': '24',
    'bac kan': '06',
    'bac ninh': '27',
    'ben tre': '83',
    'cao bang': '04',
    'ca mau': '96',
    'gia lai': '64',
    'hoa binh': '17',
    'ha giang': '02',
    'ha nam': '35',
    'ha tinh': '42',
    'hung yen': '33',
    'hai duong': '30',
    'hai phong': '31',
    'hau giang': '93',
    'khanh hoa': '56',
    'kien giang': '91',
    'kon tum': '62',
    'lai chau': '12',
    'long an': '80',
    'lao cai': '10',
    'lam dong': '68',
    'lang son': '20',
    'nam dinh': '36',
    'nghe an': '40',
    'ninh binh': '37',
    'ninh thuan': '58',
    'phu tho': '25',
    'phu yen': '54',
    'quang binh': '44',
    'quang nam': '49',
    'quang ngai': '51',
    'quang ninh': '22',
    'quang tri': '45',
    'soc trang': '94',
    'son la': '14',
    'thanh hoa': '38',
    'thai binh': '34',
    'thai nguyen': '19',
    'thua thien hue': '46',
    'tien giang': '82',
    'tra vinh': '84',
    'tuyen quang': '08',
    'tay ninh': '72',
    'vinh long': '86',
    'vinh phuc': '26',
    'yen bai': '15',
    'dien bien': '11',
    'dak lak': '66',
    'dak nong': '67',
    'dong nai': '75',
    'dong thap': '87',
    'remote': '9999',
}

ITVIEC_CITY_SLUGS: dict[str, str] = {
    'hanoi': 'ha-noi',
    'ho chi minh': 'ho-chi-minh-hcm',
    'da nang': 'da-nang',
    'bac ninh': 'bac-ninh',
    'thua thien hue': 'hue',
    'can tho': 'can-tho',
    'dong nai': 'dong-nai',
    'tay ninh': 'tay-ninh',
    'international': 'international',
    'others': 'others',
}
TOPCV_CITY_PARAMS: dict[str, tuple[str, str, str]] = {
    'hanoi': ['ha-noi', 'kl1', 'l1'],
    'ho chi minh': ['ho-chi-minh', 'kl2', 'l2'],
    'bac ninh': ['bac-ninh', 'kl4', 'l4'],
    'dong nai': ['dong-nai', 'kl5', 'l5'],
    'hung yen': ['hung-yen', 'kl6', 'l6'],
    'da nang': ['da-nang', 'kl8', 'l8'],
    'hai phong': ['hai-phong', 'kl9', 'l9'],
    'an giang': ['an-giang', 'kl10', 'l10'],
    'ca mau': ['ca-mau', 'kl19', 'l19'],
    'can tho': ['can-tho', 'kl20', 'l20'],
    'cao bang': ['cao-bang', 'kl21', 'l21'],
    'dak lak': ['dak-lak', 'kl23', 'l23'],
    'dien bien': ['dien-bien', 'kl25', 'l25'],
    'dong thap': ['dong-thap', 'kl26', 'l26'],
    'gia lai': ['gia-lai', 'kl27', 'l27'],
    'ha tinh': ['ha-tinh', 'kl30', 'l30'],
    'khanh hoa': ['khanh-hoa', 'kl33', 'l33'],
    'lai chau': ['lai-chau', 'kl36', 'l36'],
    'lam dong': ['lam-dong', 'kl37', 'l37'],
    'lang son': ['lang-son', 'kl38', 'l38'],
    'lao cai': ['lao-cai', 'kl39', 'l39'],
    'nghe an': ['nghe-an', 'kl45', 'l45'],
    'ninh binh': ['ninh-binh', 'kl46', 'l46'],
    'phu tho': ['phu-tho', 'kl48', 'l48'],
    'quang ngai': ['quang-ngai', 'kl52', 'l52'],
    'quang ninh': ['quang-ninh', 'kl53', 'l53'],
    'quang tri': ['quang-tri', 'kl54', 'l54'],
    'son la': ['son-la', 'kl56', 'l56'],
    'tay ninh': ['tay-ninh', 'kl57', 'l57'],
    'thai nguyen': ['thai-nguyen', 'kl59', 'l59'],
    'thanh hoa': ['thanh-hoa', 'kl60', 'l60'],
    'thua thien hue': ['thua-thien-hue', 'kl61', 'l61'],
    'tuyen quang': ['tuyen-quang', 'kl65', 'l65'],
    'vinh long': ['vinh-long', 'kl66', 'l66'],
    'international': ['nuoc-ngoai', 'kl100', 'l100'],
}

JOBSGO_CITY_SLUGS: dict[str, str] = {
    'hanoi': 'ha-noi',
    'ho chi minh': 'ho-chi-minh',
    'da nang': 'da-nang',
    'an giang': 'an-giang',
    'ba ria vung tau': 'ba-ria-vung-tau',
    'binh duong': 'binh-duong',
    'binh dinh': 'binh-dinh',
    'binh phuoc': 'binh-phuoc',
    'binh thuan': 'binh-thuan',
    'bac lieu': 'bac-lieu',
    'bac giang': 'bac-giang',
    'bac kan': 'bac-kan',
    'bac ninh': 'bac-ninh',
    'ben tre': 'ben-tre',
    'cao bang': 'cao-bang',
    'ca mau': 'ca-mau',
    'can tho': 'can-tho',
    'dien bien': 'dien-bien',
    'dak lak': 'dak-lak',
    'dak nong': 'dak-nong',
    'dong nai': 'dong-nai',
    'dong thap': 'dong-thap',
    'gia lai': 'gia-lai',
    'ha giang': 'ha-giang',
    'ha nam': 'ha-nam',
    'ha tinh': 'ha-tinh',
    'hung yen': 'hung-yen',
    'hai duong': 'hai-duong',
    'hai phong': 'hai-phong',
    'hau giang': 'hau-giang',
    'khanh hoa': 'khanh-hoa',
    'kien giang': 'kien-giang',
    'kon tum': 'kon-tum',
    'lai chau': 'lai-chau',
    'long an': 'long-an',
    'lao cai': 'lao-cai',
    'lam dong': 'lam-dong',
    'lang son': 'lang-son',
    'nam dinh': 'nam-dinh',
    'nghe an': 'nghe-an',
    'ninh binh': 'ninh-binh',
    'ninh thuan': 'ninh-thuan',
    'phu tho': 'phu-tho',
    'phu yen': 'phu-yen',
    'quang binh': 'quang-binh',
    'quang nam': 'quang-nam',
    'quang ngai': 'quang-ngai',
    'quang ninh': 'quang-ninh',
    'quang tri': 'quang-tri',
    'soc trang': 'soc-trang',
    'son la': 'son-la',
    'thanh hoa': 'thanh-hoa',
    'thai binh': 'thai-binh',
    'thai nguyen': 'thai-nguyen',
    'thua thien hue': 'thua-thien-hue',
    'tien giang': 'tien-giang',
    'tra vinh': 'tra-vinh',
    'tuyen quang': 'tuyen-quang',
    'tay ninh': 'tay-ninh',
    'vinh long': 'vinh-long',
    'vinh phuc': 'vinh-phuc',
    'yen bai': 'yen-bai',
}
VIECO_CITY_PARAMS: dict[str, tuple[str, str]] = {
    'ho chi minh': ['khu-vuc-ho-chi-minh', '1'],
    'hanoi': ['khu-vuc-ha-noi', '62'],
    'da nang': ['khu-vuc-da-nang', '2'],
    'hai phong': ['khu-vuc-hai-phong', '64'],
    'can tho': ['khu-vuc-can-tho', '63'],
    'an giang': ['khu-vuc-an-giang', '4'],
    'ba ria vung tau': ['khu-vuc-ba-ria-vung-tau', '5'],
    'bac giang': ['khu-vuc-bac-giang', '6'],
    'bac kan': ['khu-vuc-bac-kan', '7'],
    'bac lieu': ['khu-vuc-bac-lieu', '8'],
    'bac ninh': ['khu-vuc-bac-ninh', '9'],
    'ben tre': ['khu-vuc-ben-tre', '10'],
    'binh duong': ['khu-vuc-binh-duong', '12'],
    'binh dinh': ['khu-vuc-binh-dinh', '11'],
    'binh phuoc': ['khu-vuc-binh-phuoc', '13'],
    'binh thuan': ['khu-vuc-binh-thuan', '14'],
    'ca mau': ['khu-vuc-ca-mau', '15'],
    'cao bang': ['khu-vuc-cao-bang', '16'],
    'dak lak': ['khu-vuc-dak-lak', '17'],
    'dak nong': ['khu-vuc-dak-nong', '18'],
    'dien bien': ['khu-vuc-dien-bien', '19'],
    'dong nai': ['khu-vuc-dong-nai', '20'],
    'dong thap': ['khu-vuc-dong-thap', '21'],
    'gia lai': ['khu-vuc-gia-lai', '22'],
    'ha giang': ['khu-vuc-ha-giang', '23'],
    'ha nam': ['khu-vuc-ha-nam', '24'],
    'ha tinh': ['khu-vuc-ha-tinh', '25'],
    'hai duong': ['khu-vuc-hai-duong', '26'],
    'hau giang': ['khu-vuc-hau-giang', '27'],
    'hoa binh': ['khu-vuc-hoa-binh', '28'],
    'hung yen': ['khu-vuc-hung-yen', '29'],
    'khanh hoa': ['khu-vuc-khanh-hoa', '30'],
    'kien giang': ['khu-vuc-kien-giang', '31'],
    'kon tum': ['khu-vuc-kon-tum', '32'],
    'lai chau': ['khu-vuc-lai-chau', '33'],
    'lam dong': ['khu-vuc-lam-dong', '34'],
    'lang son': ['khu-vuc-lang-son', '35'],
    'lao cai': ['khu-vuc-lao-cai', '36'],
    'long an': ['khu-vuc-long-an', '37'],
    'nam dinh': ['khu-vuc-nam-dinh', '38'],
    'nghe an': ['khu-vuc-nghe-an', '39'],
    'ninh binh': ['khu-vuc-ninh-binh', '40'],
    'ninh thuan': ['khu-vuc-ninh-thuan', '41'],
    'phu tho': ['khu-vuc-phu-tho', '42'],
    'phu yen': ['khu-vuc-phu-yen', '61'],
    'quang binh': ['khu-vuc-quang-binh', '43'],
    'quang nam': ['khu-vuc-quang-nam', '44'],
    'quang ngai': ['khu-vuc-quang-ngai', '45'],
    'quang ninh': ['khu-vuc-quang-ninh', '46'],
    'quang tri': ['khu-vuc-quang-tri', '47'],
    'soc trang': ['khu-vuc-soc-trang', '48'],
    'son la': ['khu-vuc-son-la', '49'],
    'tay ninh': ['khu-vuc-tay-ninh', '50'],
    'thai binh': ['khu-vuc-thai-binh', '51'],
    'thai nguyen': ['khu-vuc-thai-nguyen', '52'],
    'thanh hoa': ['khu-vuc-thanh-hoa', '53'],
    'thua thien hue': ['khu-vuc-thua-thien-hue', '54'],
    'tien giang': ['khu-vuc-tien-giang', '55'],
    'tra vinh': ['khu-vuc-tra-vinh', '56'],
    'tuyen quang': ['khu-vuc-tuyen-quang', '57'],
    'vinh long': ['khu-vuc-vinh-long', '58'],
    'vinh phuc': ['khu-vuc-vinh-phuc', '59'],
    'yen bai': ['khu-vuc-yen-bai', '60'],
    'others': ['khu-vuc-khac', '65'],
}
CAREERVIET_CITY_IDS: dict[str, str] = {
    'hanoi': '4',
    'ho chi minh': '8',
    'hoa binh': '18',
    'ha giang': '19',
    'lao cai': '20',
    'son la': '22',
    'cao bang': '26',
    'ninh binh': '30',
    'hai phong': '31',
    'thai binh': '36',
    'thanh hoa': '37',
    'nghe an': '38',
    'ha tinh': '39',
    'dak lak': '50',
    'thua thien hue': '54',
    'quang ngai': '55',
    'binh dinh': '56',
    'khanh hoa': '58',
    'gia lai': '59',
    'kon tum': '60',
    'dong nai': '61',
    'binh thuan': '62',
    'ba ria vung tau': '64',
    'tay ninh': '66',
    'dong thap': '67',
    'ninh thuan': '68',
    'vinh long': '70',
    'can tho': '71',
    'long an': '72',
    'tien giang': '73',
    'tra vinh': '74',
    'ben tre': '75',
    'an giang': '76',
    'kien giang': '77',
    'ca mau': '78',
    'soc trang': '79',
    'phu tho': '210',
    'vinh phuc': '211',
    'bac giang': '240',
    'bac ninh': '241',
    'thai nguyen': '280',
    'hai duong': '320',
    'hung yen': '321',
    'nam dinh': '350',
    'ha nam': '351',
    'quang nam': '510',
    'da nang': '511',
    'binh duong': '650',
    'binh phuoc': '651',
    'hau giang': '780',
    'bac lieu': '781',
    'dien bien': '900',
}

INDEED_CITY_PARAMS: dict[str, str] = {    'ho chi minh': 'Ho Chi Minh City',
    'thanh hoa': 'Thanh Hoa',
    'tay ninh': 'Tây Ninh',
    'hai duong': 'Hải Dương',
    'vinh long': 'Vĩnh Long',
    'quang ngai': 'Quảng Ngãi',
    'bac giang': 'Bắc Giang',
    'bac kan': 'Bắc Kạn',
    'bac lieu': 'Bạc Liêu',
    'ben tre': 'Bến Tre',
    'ca mau': 'Cà Mau',
    'cao bang': 'Cao Bằng',
    'dien bien': 'Điện Biên Phủ',
    'ha giang': 'Hà Giang',
    'ha tinh': 'Hà Tĩnh',
    'hoa binh': 'Hòa Bình',
    'hung yen': 'Hưng Yên',
    'kon tum': 'Kon Tum',
    'lai chau': 'Lai Châu',
    'lang son': 'Lang Son',
    'lao cai': 'Lao Cai',
    'nam dinh': 'Nam Định',
    'ninh binh': 'Ninh Binh',
    'soc trang': 'Sóc Trăng',
    'son la': 'Son La',
    'thai binh': 'Thái Bình',
    'tra vinh': 'Trà Vinh',
    'tuyen quang': 'Tuyên Quang',
    'yen bai': 'Yên Bái',
    'an giang': 'An Giang',
    'dak lak': 'Đắk Lắk',
    'dong nai': 'Đồng Nai',
    'dong thap': 'Đồng Tháp',
    'gia lai': 'Gia Lai',
    'khanh hoa': 'Khánh Hòa',
    'lam dong': 'Lâm Đồng',
    'nghe an': 'Nghệ An',
    'phu tho': 'Phú Thọ',
    'quang ninh': 'Quảng Ninh',
    'quang tri': 'Quảng Trị',
    'thua thien hue': 'Thừa Thiên - Huế',
    'ba ria vung tau': 'Vũng Tàu',
    'hanoi': 'Hà Nội',
    'da nang': 'Đà Nẵng',
    'can tho': 'Cần Thơ',
    'hai phong': 'Hai Phong',
    'thai nguyen': 'Thái Nguyên',
    'bac ninh': 'Bắc Ninh',
}

# Source -> canonical city map (used to skip sources that don't support a city)
SOURCE_CITY_MAPS: dict[str, dict] = {
    "vietnamworks": VIETNAMWORKS_CITY_IDS,
    "topdev": TOPDEV_REGION_IDS,
    "itviec": ITVIEC_CITY_SLUGS,
    "topcv": TOPCV_CITY_PARAMS,
    "jobsgo": JOBSGO_CITY_SLUGS,
    "viecoi": VIECO_CITY_PARAMS,
    "indeed": INDEED_CITY_PARAMS,
    "careerviet": CAREERVIET_CITY_IDS,
}

# TopDev job level ids (from /td/v2/taxonomies?fields=job_levels)
TOPDEV_LEVEL_IDS: dict[str, str] = {
    "intern": "1616",
    "fresher": "12507",
    "junior": "1617",
    "middle": "12506",
    "senior": "1618",
    "lead": "12052",
    "manager": "1619",
    "director": "1620",
}

USER_AGENTS: list[str] = [
    (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/126.0.0.0 Safari/537.36"
    ),
    (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/125.0.0.0 Safari/537.36"
    ),
    (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    (
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/123.0.0.0 Safari/537.36"
    ),
    (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) "
        "Version/17.4 Safari/605.1.15"
    ),
]

REQUEST_TIMEOUT: float = float(os.environ.get("CRAWLER_TIMEOUT", "20"))
MAX_RETRIES: int = int(os.environ.get("CRAWLER_MAX_RETRIES", "3"))
RETRY_BACKOFF: float = float(os.environ.get("CRAWLER_RETRY_BACKOFF", "1.0"))
PER_SOURCE_DELAY: float = float(os.environ.get("CRAWLER_SOURCE_DELAY", "0.8"))
SOURCE_TIMEOUT: float = float(os.environ.get("CRAWLER_SOURCE_TIMEOUT", "45"))

# ---- BrightData Web Unlocker (lớp bypass trả phí) ----
# Có CRAWLER_BRIGHTDATA_KEY là bật bypass: requests bị chặn (403/429/CF)
# sẽ được lấy qua API BrightData thay vì browser/proxy như trước.
BRIGHTDATA_KEY: str | None = (
    os.environ.get("CRAWLER_BRIGHTDATA_KEY") or os.environ.get("BRIGHTDATA_API_KEY")
)
BRIGHTDATA_URL: str = os.environ.get(
    "CRAWLER_BRIGHTDATA_URL", "https://api.brightdata.com/request"
)
BRIGHTDATA_ZONE: str = os.environ.get("CRAWLER_BRIGHTDATA_ZONE", "web_unlocker1")
BRIGHTDATA_COUNTRY: str | None = os.environ.get("CRAWLER_BRIGHTDATA_COUNTRY") or None

DISABLED_SOURCES: set[str] = {
    s.strip() for s in os.environ.get("CRAWLER_DISABLE_SOURCES", "").split(",") if s.strip()
}

HEADERS_TEMPLATE: dict[str, str] = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Accept-Language": "vi-VN,vi;q=0.9,en-US;q=0.8,en;q=0.7",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "none",
    "Sec-Fetch-User": "?1",
    "sec-ch-ua": '"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
}
