import { MigrationInterface, QueryRunner } from "typeorm";

export class AddUserNotifications1785854058795 implements MigrationInterface {
    name = 'AddUserNotifications1785854058795'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_sessions" DROP CONSTRAINT "FK_refresh_sessions_user"`);
        await queryRunner.query(`ALTER TABLE "job_search_intents" DROP CONSTRAINT "FK_job_search_intents_audit"`);
        await queryRunner.query(`ALTER TABLE "job_search_intents" DROP CONSTRAINT "FK_job_search_intents_user"`);
        await queryRunner.query(`ALTER TABLE "job_crawl_runs" DROP CONSTRAINT "FK_job_crawl_runs_intent"`);
        await queryRunner.query(`ALTER TABLE "job_intent_matches" DROP CONSTRAINT "FK_job_intent_matches_intent"`);
        await queryRunner.query(`ALTER TABLE "job_intent_matches" DROP CONSTRAINT "FK_job_intent_matches_job"`);
        await queryRunner.query(`ALTER TABLE "user_cvs" DROP CONSTRAINT "FK_user_cvs_user"`);
        await queryRunner.query(`ALTER TABLE "cv_audits" DROP CONSTRAINT "FK_cv_audits_user"`);
        await queryRunner.query(`ALTER TABLE "cv_audits" DROP CONSTRAINT "FK_cv_audits_user_cv"`);
        await queryRunner.query(`ALTER TABLE "cv_audit_batches" DROP CONSTRAINT "FK_cv_audit_batches_audit"`);
        await queryRunner.query(`ALTER TABLE "job_family_category_edges" DROP CONSTRAINT "FK_job_family_category_edges_parent"`);
        await queryRunner.query(`ALTER TABLE "job_family_category_edges" DROP CONSTRAINT "FK_job_family_category_edges_child"`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" DROP CONSTRAINT "FK_cv_research_sessions_user"`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" DROP CONSTRAINT "FK_cv_research_sessions_user_cv"`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" DROP CONSTRAINT "FK_cv_research_sessions_cv_audit"`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" DROP CONSTRAINT "FK_cv_research_sessions_job_intent"`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" DROP CONSTRAINT "FK_cv_research_sessions_category"`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" DROP CONSTRAINT "FK_cv_research_sessions_seniority"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_job_search_intents_user_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_job_posts_last_seen_at"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_job_intent_matches_intent_job"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_job_intent_matches_score"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cv_audits_user_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_job_family_category_edges_parent"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_job_family_category_edges_child"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_job_family_categories_level"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_job_family_categories_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_job_family_categories_search_text"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_seniority_levels_active_order"`);
        await queryRunner.query(`ALTER TABLE "cv_audit_batches" DROP CONSTRAINT "UQ_cv_audit_batches_audit_batch"`);
        await queryRunner.query(`CREATE TABLE "user_notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "resource_type" character varying NOT NULL, "resource_id" uuid NOT NULL, "status" character varying NOT NULL, "title" character varying NOT NULL, "message" character varying NOT NULL, "href" character varying NOT NULL, "read_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_569622b0fd6e6ab3661de985a2b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_user_notifications_resource" ON "user_notifications"  ("user_id", "resource_type", "resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_notifications_user_created" ON "user_notifications"  ("user_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_users_username"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_users_email"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_users_google_id"`);
        await queryRunner.query(`ALTER TABLE "job_search_intents" ALTER COLUMN "keywords" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "job_search_intents" ALTER COLUMN "search_queries" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "job_search_intents" ALTER COLUMN "locations" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "job_search_intents" ALTER COLUMN "completed_sources" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "job_crawl_runs" ALTER COLUMN "query" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "job_posts" ALTER COLUMN "locations" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "job_posts" ALTER COLUMN "skills" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "job_posts" ALTER COLUMN "raw" SET DEFAULT '{}'::jsonb`);
        await queryRunner.query(`ALTER TABLE "job_intent_matches" ALTER COLUMN "matched_terms" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "user_cvs" ALTER COLUMN "parsed_lines" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" ALTER COLUMN "job_suggestions_snapshot" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users"  ("username") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users"  ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0bd5012aeb82628e07f6a1be53" ON "users"  ("google_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b95a452accdf44b9690dfb6491" ON "cv_audit_batches"  ("audit_id", "batch_index") `);
        await queryRunner.query(`ALTER TABLE "refresh_sessions" ADD CONSTRAINT "FK_a7ab4fd82c654c85b9de53d971a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_search_intents" ADD CONSTRAINT "FK_8b7f0fdc62efe4071729908ef4f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_crawl_runs" ADD CONSTRAINT "FK_8edb933434d20858dd2bc713023" FOREIGN KEY ("intent_id") REFERENCES "job_search_intents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_intent_matches" ADD CONSTRAINT "FK_090c2159c29a09776ee227b0fad" FOREIGN KEY ("intent_id") REFERENCES "job_search_intents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_intent_matches" ADD CONSTRAINT "FK_0ae446b942d2e433139450bac87" FOREIGN KEY ("job_post_id") REFERENCES "job_posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_cvs" ADD CONSTRAINT "FK_34bc925d8396bd3b0179bd905c2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_audits" ADD CONSTRAINT "FK_914a58944d492177f71846ebdba" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_audits" ADD CONSTRAINT "FK_31eb20832ad1222b3ccfe9bef7f" FOREIGN KEY ("user_cv_id") REFERENCES "user_cvs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_audit_batches" ADD CONSTRAINT "FK_e12243eb040848da097165d1150" FOREIGN KEY ("audit_id") REFERENCES "cv_audits"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_family_category_edges" ADD CONSTRAINT "FK_f7d483b8e0fb5c4fdfd98c0d70f" FOREIGN KEY ("parent_id") REFERENCES "job_family_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_family_category_edges" ADD CONSTRAINT "FK_f029770cf99fd328c7741d7532d" FOREIGN KEY ("child_id") REFERENCES "job_family_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" ADD CONSTRAINT "FK_c8775d3ad651ad99234aa927bff" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" ADD CONSTRAINT "FK_f281c1dec7edb2705a9dde9e3f4" FOREIGN KEY ("user_cv_id") REFERENCES "user_cvs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" ADD CONSTRAINT "FK_af3e1e6fdae749ae2b67b74ad71" FOREIGN KEY ("cv_audit_id") REFERENCES "cv_audits"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" ADD CONSTRAINT "FK_af1af9e39558934823d3a6fbfb2" FOREIGN KEY ("job_search_intent_id") REFERENCES "job_search_intents"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" ADD CONSTRAINT "FK_eab8561f6b71b884b711362b943" FOREIGN KEY ("job_category_id") REFERENCES "job_family_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" ADD CONSTRAINT "FK_ed8d3b03743a6440856bf5eb242" FOREIGN KEY ("seniority_level_id") REFERENCES "seniority_levels"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" DROP CONSTRAINT "FK_ed8d3b03743a6440856bf5eb242"`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" DROP CONSTRAINT "FK_eab8561f6b71b884b711362b943"`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" DROP CONSTRAINT "FK_af1af9e39558934823d3a6fbfb2"`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" DROP CONSTRAINT "FK_af3e1e6fdae749ae2b67b74ad71"`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" DROP CONSTRAINT "FK_f281c1dec7edb2705a9dde9e3f4"`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" DROP CONSTRAINT "FK_c8775d3ad651ad99234aa927bff"`);
        await queryRunner.query(`ALTER TABLE "job_family_category_edges" DROP CONSTRAINT "FK_f029770cf99fd328c7741d7532d"`);
        await queryRunner.query(`ALTER TABLE "job_family_category_edges" DROP CONSTRAINT "FK_f7d483b8e0fb5c4fdfd98c0d70f"`);
        await queryRunner.query(`ALTER TABLE "cv_audit_batches" DROP CONSTRAINT "FK_e12243eb040848da097165d1150"`);
        await queryRunner.query(`ALTER TABLE "cv_audits" DROP CONSTRAINT "FK_31eb20832ad1222b3ccfe9bef7f"`);
        await queryRunner.query(`ALTER TABLE "cv_audits" DROP CONSTRAINT "FK_914a58944d492177f71846ebdba"`);
        await queryRunner.query(`ALTER TABLE "user_cvs" DROP CONSTRAINT "FK_34bc925d8396bd3b0179bd905c2"`);
        await queryRunner.query(`ALTER TABLE "job_intent_matches" DROP CONSTRAINT "FK_0ae446b942d2e433139450bac87"`);
        await queryRunner.query(`ALTER TABLE "job_intent_matches" DROP CONSTRAINT "FK_090c2159c29a09776ee227b0fad"`);
        await queryRunner.query(`ALTER TABLE "job_crawl_runs" DROP CONSTRAINT "FK_8edb933434d20858dd2bc713023"`);
        await queryRunner.query(`ALTER TABLE "job_search_intents" DROP CONSTRAINT "FK_8b7f0fdc62efe4071729908ef4f"`);
        await queryRunner.query(`ALTER TABLE "refresh_sessions" DROP CONSTRAINT "FK_a7ab4fd82c654c85b9de53d971a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b95a452accdf44b9690dfb6491"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0bd5012aeb82628e07f6a1be53"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" ALTER COLUMN "job_suggestions_snapshot" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "user_cvs" ALTER COLUMN "parsed_lines" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "job_intent_matches" ALTER COLUMN "matched_terms" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "job_posts" ALTER COLUMN "raw" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "job_posts" ALTER COLUMN "skills" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "job_posts" ALTER COLUMN "locations" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "job_crawl_runs" ALTER COLUMN "query" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "job_search_intents" ALTER COLUMN "completed_sources" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "job_search_intents" ALTER COLUMN "locations" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "job_search_intents" ALTER COLUMN "search_queries" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "job_search_intents" ALTER COLUMN "keywords" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_users_google_id" UNIQUE ("google_id")`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_users_email" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_users_username" UNIQUE ("username")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_notifications_user_created"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_user_notifications_resource"`);
        await queryRunner.query(`DROP TABLE "user_notifications"`);
        await queryRunner.query(`ALTER TABLE "cv_audit_batches" ADD CONSTRAINT "UQ_cv_audit_batches_audit_batch" UNIQUE ("audit_id", "batch_index")`);
        await queryRunner.query(`CREATE INDEX "IDX_seniority_levels_active_order" ON "seniority_levels" USING btree ("display_order", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_job_family_categories_search_text" ON "job_family_categories" USING btree ("search_text") `);
        await queryRunner.query(`CREATE INDEX "IDX_job_family_categories_name" ON "job_family_categories" USING btree ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_job_family_categories_level" ON "job_family_categories" USING btree ("level") `);
        await queryRunner.query(`CREATE INDEX "IDX_job_family_category_edges_child" ON "job_family_category_edges" USING btree ("child_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_job_family_category_edges_parent" ON "job_family_category_edges" USING btree ("parent_id", "position") `);
        await queryRunner.query(`CREATE INDEX "IDX_cv_audits_user_created" ON "cv_audits" USING btree ("created_at", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_job_intent_matches_score" ON "job_intent_matches" USING btree ("intent_id", "match_score") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_job_intent_matches_intent_job" ON "job_intent_matches" USING btree ("intent_id", "job_post_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_job_posts_last_seen_at" ON "job_posts" USING btree ("last_seen_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_job_search_intents_user_created" ON "job_search_intents" USING btree ("created_at", "user_id") `);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" ADD CONSTRAINT "FK_cv_research_sessions_seniority" FOREIGN KEY ("seniority_level_id") REFERENCES "seniority_levels"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" ADD CONSTRAINT "FK_cv_research_sessions_category" FOREIGN KEY ("job_category_id") REFERENCES "job_family_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" ADD CONSTRAINT "FK_cv_research_sessions_job_intent" FOREIGN KEY ("job_search_intent_id") REFERENCES "job_search_intents"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" ADD CONSTRAINT "FK_cv_research_sessions_cv_audit" FOREIGN KEY ("cv_audit_id") REFERENCES "cv_audits"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" ADD CONSTRAINT "FK_cv_research_sessions_user_cv" FOREIGN KEY ("user_cv_id") REFERENCES "user_cvs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_research_sessions" ADD CONSTRAINT "FK_cv_research_sessions_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_family_category_edges" ADD CONSTRAINT "FK_job_family_category_edges_child" FOREIGN KEY ("child_id") REFERENCES "job_family_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_family_category_edges" ADD CONSTRAINT "FK_job_family_category_edges_parent" FOREIGN KEY ("parent_id") REFERENCES "job_family_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_audit_batches" ADD CONSTRAINT "FK_cv_audit_batches_audit" FOREIGN KEY ("audit_id") REFERENCES "cv_audits"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_audits" ADD CONSTRAINT "FK_cv_audits_user_cv" FOREIGN KEY ("user_cv_id") REFERENCES "user_cvs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv_audits" ADD CONSTRAINT "FK_cv_audits_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_cvs" ADD CONSTRAINT "FK_user_cvs_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_intent_matches" ADD CONSTRAINT "FK_job_intent_matches_job" FOREIGN KEY ("job_post_id") REFERENCES "job_posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_intent_matches" ADD CONSTRAINT "FK_job_intent_matches_intent" FOREIGN KEY ("intent_id") REFERENCES "job_search_intents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_crawl_runs" ADD CONSTRAINT "FK_job_crawl_runs_intent" FOREIGN KEY ("intent_id") REFERENCES "job_search_intents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_search_intents" ADD CONSTRAINT "FK_job_search_intents_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_search_intents" ADD CONSTRAINT "FK_job_search_intents_audit" FOREIGN KEY ("audit_id") REFERENCES "cv_audits"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_sessions" ADD CONSTRAINT "FK_refresh_sessions_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
