import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateSaasBillingAdminAndCrawlRuns1788700000000 implements MigrationInterface {
  name = 'CreateSaasBillingAdminAndCrawlRuns1788700000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying NOT NULL DEFAULT 'user'`);
    await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "CHK_users_role" CHECK ("role" IN ('user','admin'))`);
    await queryRunner.query(`CREATE TABLE "service_products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "description" text, "price_credits" bigint NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "version" integer NOT NULL DEFAULT 1, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "CHK_service_products_price" CHECK ("price_credits" >= 0), CONSTRAINT "UQ_service_products_code" UNIQUE ("code"), CONSTRAINT "PK_service_products" PRIMARY KEY ("id"))`);
    await queryRunner.query(`INSERT INTO "service_products" ("id", "code", "name", "description", "price_credits") VALUES ('20000000-0000-4000-8000-000000000001', 'quick_research', 'Research nhanh', 'AI suy luận ngành và cấp bậc từ CV, audit CV và gợi ý việc làm phù hợp.', 12), ('20000000-0000-4000-8000-000000000002', 'manual_research', 'Research tùy chỉnh', 'Audit CV theo ngành, cấp bậc và địa điểm do người dùng lựa chọn.', 10)`);
    await queryRunner.query(`CREATE TABLE "credit_accounts" ("user_id" uuid NOT NULL, "balance" bigint NOT NULL DEFAULT 0, "version" integer NOT NULL DEFAULT 1, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "CHK_credit_accounts_balance" CHECK ("balance" >= 0), CONSTRAINT "PK_credit_accounts" PRIMARY KEY ("user_id"), CONSTRAINT "FK_credit_accounts_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE)`);
    await queryRunner.query(`CREATE TABLE "credit_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" character varying NOT NULL, "amount_delta" bigint NOT NULL, "balance_before" bigint NOT NULL, "balance_after" bigint NOT NULL, "service_product_id" uuid, "research_session_id" uuid, "actor_user_id" uuid, "idempotency_key" character varying NOT NULL, "reason" text, "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_credit_transactions_idempotency" UNIQUE ("idempotency_key"), CONSTRAINT "CHK_credit_transactions_balance" CHECK ("balance_before" >= 0 AND "balance_after" >= 0 AND "balance_after" = "balance_before" + "amount_delta"), CONSTRAINT "PK_credit_transactions" PRIMARY KEY ("id"), CONSTRAINT "FK_credit_transactions_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE, CONSTRAINT "FK_credit_transactions_actor" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE SET NULL, CONSTRAINT "FK_credit_transactions_product" FOREIGN KEY ("service_product_id") REFERENCES "service_products"("id") ON DELETE SET NULL, CONSTRAINT "FK_credit_transactions_session" FOREIGN KEY ("research_session_id") REFERENCES "cv_research_sessions"("id") ON DELETE SET NULL)`);
    await queryRunner.query(`CREATE INDEX "IDX_credit_transactions_user_created" ON "credit_transactions" ("user_id", "created_at" DESC)`);
    await queryRunner.query(`CREATE TABLE "service_usages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "service_product_id" uuid NOT NULL, "service_code" character varying NOT NULL, "service_name" character varying NOT NULL, "unit_price_credits" bigint NOT NULL, "quantity" integer NOT NULL DEFAULT 1, "total_credits" bigint NOT NULL, "research_session_id" uuid NOT NULL, "attempt" integer NOT NULL, "status" character varying NOT NULL DEFAULT 'reserved', "reserved_at" TIMESTAMP NOT NULL, "settled_at" TIMESTAMP, "refunded_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_service_usages_session_attempt" UNIQUE ("research_session_id", "attempt"), CONSTRAINT "CHK_service_usages_values" CHECK ("quantity" > 0 AND "unit_price_credits" >= 0 AND "total_credits" = "unit_price_credits" * "quantity"), CONSTRAINT "CHK_service_usages_status" CHECK ("status" IN ('reserved','consumed','refunded')), CONSTRAINT "PK_service_usages" PRIMARY KEY ("id"), CONSTRAINT "FK_service_usages_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE, CONSTRAINT "FK_service_usages_product" FOREIGN KEY ("service_product_id") REFERENCES "service_products"("id") ON DELETE RESTRICT, CONSTRAINT "FK_service_usages_session" FOREIGN KEY ("research_session_id") REFERENCES "cv_research_sessions"("id") ON DELETE CASCADE)`);
    await queryRunner.query(`CREATE TABLE "activity_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subject_user_id" uuid, "actor_user_id" uuid, "action" character varying NOT NULL, "resource_type" character varying, "resource_id" character varying, "status" character varying NOT NULL DEFAULT 'success', "ip_address" character varying, "user_agent" text, "metadata" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_activity_logs" PRIMARY KEY ("id"), CONSTRAINT "FK_activity_logs_subject" FOREIGN KEY ("subject_user_id") REFERENCES "users"("id") ON DELETE SET NULL, CONSTRAINT "FK_activity_logs_actor" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE SET NULL)`);
    await queryRunner.query(`CREATE INDEX "IDX_activity_logs_subject_created" ON "activity_logs" ("subject_user_id", "created_at" DESC)`);
    await queryRunner.query(`CREATE INDEX "IDX_activity_logs_actor_created" ON "activity_logs" ("actor_user_id", "created_at" DESC)`);
    await queryRunner.query(`CREATE TABLE "category_crawl_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trigger_key" character varying NOT NULL, "trigger_type" character varying NOT NULL, "triggered_by_user_id" uuid, "status" character varying NOT NULL DEFAULT 'queued', "phase" character varying NOT NULL DEFAULT 'queued', "progress" smallint NOT NULL DEFAULT 0, "progress_message" character varying, "total_targets" integer NOT NULL DEFAULT 0, "completed_targets" integer NOT NULL DEFAULT 0, "failed_targets" integer NOT NULL DEFAULT 0, "total_jobs" integer NOT NULL DEFAULT 0, "saved_jobs" integer NOT NULL DEFAULT 0, "current_source" character varying, "current_category" character varying, "cancel_requested" boolean NOT NULL DEFAULT false, "bull_job_id" character varying, "report_snapshot" jsonb, "error" text, "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_category_crawl_runs_trigger_key" UNIQUE ("trigger_key"), CONSTRAINT "CHK_category_crawl_runs_progress" CHECK ("progress" BETWEEN 0 AND 100), CONSTRAINT "PK_category_crawl_runs" PRIMARY KEY ("id"), CONSTRAINT "FK_category_crawl_runs_user" FOREIGN KEY ("triggered_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL)`);
    await queryRunner.query(`CREATE INDEX "IDX_category_crawl_runs_created" ON "category_crawl_runs" ("created_at" DESC)`);
    await queryRunner.query(`CREATE UNIQUE INDEX "UQ_category_crawl_runs_active" ON "category_crawl_runs" ((1)) WHERE "status" IN ('queued','processing')`);
    await queryRunner.query(`CREATE TABLE "category_crawl_run_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "run_id" uuid NOT NULL, "source" character varying NOT NULL, "crawl_url" text NOT NULL, "category_ids" jsonb NOT NULL DEFAULT '[]', "category_names" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'queued', "fetched_count" integer NOT NULL DEFAULT 0, "saved_count" integer NOT NULL DEFAULT 0, "duration_ms" integer, "error" text, "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_category_crawl_run_items_target" UNIQUE ("run_id", "source", "crawl_url"), CONSTRAINT "PK_category_crawl_run_items" PRIMARY KEY ("id"), CONSTRAINT "FK_category_crawl_run_items_run" FOREIGN KEY ("run_id") REFERENCES "category_crawl_runs"("id") ON DELETE CASCADE)`);
    await queryRunner.query(`INSERT INTO "credit_accounts" ("user_id", "balance") SELECT "id", GREATEST("credits", 0)::bigint FROM "users"`);
    await queryRunner.query(`INSERT INTO "credit_transactions" ("user_id", "type", "amount_delta", "balance_before", "balance_after", "idempotency_key", "reason") SELECT "id", 'opening_balance', GREATEST("credits", 0)::bigint, 0, GREATEST("credits", 0)::bigint, 'opening:' || "id"::text, 'Số dư chuyển từ hệ thống cũ' FROM "users"`);
    await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "credits"`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "users" ADD "credits" integer NOT NULL DEFAULT 0`);
    await queryRunner.query(`UPDATE "users" u SET "credits" = LEAST(a."balance", 2147483647)::integer FROM "credit_accounts" a WHERE a."user_id" = u."id"`);
    await queryRunner.query(`DROP TABLE "category_crawl_run_items"`);
    await queryRunner.query(`DROP INDEX "public"."UQ_category_crawl_runs_active"`);
    await queryRunner.query(`DROP TABLE "category_crawl_runs"`);
    await queryRunner.query(`DROP TABLE "activity_logs"`);
    await queryRunner.query(`DROP TABLE "service_usages"`);
    await queryRunner.query(`DROP TABLE "credit_transactions"`);
    await queryRunner.query(`DROP TABLE "credit_accounts"`);
    await queryRunner.query(`DROP TABLE "service_products"`);
    await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "CHK_users_role"`);
    await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
  }
}
